# Generated by Django 5.0 on 2023-12-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitiruvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='jamoa_rasm')),
                ('ism_sharif', models.CharField(max_length=200)),
                ('tarix', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bitiruvchi',
                'verbose_name_plural': 'Bitiruvchilar',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='jamoa_rasm')),
                ('nom', models.CharField(max_length=200)),
                ('sana', models.DateTimeField()),
                ('batafsil', models.TextField(blank=True, null=True)),
                ('viewed', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Bloglar',
            },
        ),
        migrations.CreateModel(
            name='Galereya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='jamoa_rasm')),
            ],
            options={
                'verbose_name': 'Galereya',
                'verbose_name_plural': 'Galereyalar',
            },
        ),
        migrations.CreateModel(
            name='Jamoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='jamoa_rasm')),
                ('ism_sharif', models.CharField(max_length=200)),
                ('vazifa', models.CharField(max_length=200)),
                ('telegram', models.CharField(blank=True, max_length=200, null=True)),
                ('telefon', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Jamoa',
                'verbose_name_plural': 'Jamoa',
            },
        ),
        migrations.CreateModel(
            name='Kurslar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='jamoa_rasm')),
                ('nomi', models.CharField(max_length=200)),
                ('kurs_davomiyligi', models.CharField(max_length=200)),
                ('dars_davomiyligi', models.CharField(max_length=200)),
                ('narxi', models.CharField(max_length=100)),
                ('oqituvchi', models.CharField(max_length=13)),
                ('boglanish', models.CharField(max_length=13)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Markaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='jamoa_rasm')),
                ('markaz_nomi', models.CharField(max_length=200)),
                ('malumot', models.TextField()),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('telefon', models.IntegerField(blank=True, null=True)),
                ('oquvchilar', models.IntegerField()),
                ('yonalishlar', models.IntegerField()),
                ('kurslar', models.IntegerField()),
                ('hodimlar', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Markaz',
                'verbose_name_plural': 'Markaz',
            },
        ),
        migrations.CreateModel(
            name='VideoKontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=500)),
                ('sana', models.DateTimeField()),
                ('link', models.URLField(help_text="youtu.be ning o'rniga youtube.com/embed so'zini kiriting")),
            ],
            options={
                'verbose_name': 'Video Kontent',
                'verbose_name_plural': 'Video kontentlar',
            },
        ),
        migrations.CreateModel(
            name='Xizmatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='jamoa_rasm')),
                ('nomi', models.CharField(max_length=200)),
                ('batafsil', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
            },
        ),
    ]
